services:
  cypress-tests:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: cypress-tests
    environment:
      - xAuthS=${xAuthS}
      - xAuthU=${xAuthU}
    command: npm run silent:api -- --env xAuthS=${xAuthS},xAuthU=${xAuthU}